version: '3.1'
services:
#    mailhog:
#        image: 'mailhog/mailhog:latest'
#        ports:
#            - '58001:8025'
#
#    redis:
#        image: 'redis:alpine'

    mariadb:
        image: 'mariadb:10.8'
        working_dir: /application
        volumes:
            - './app:/application'
            - './.docker/mariadb/data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - '58003:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './app:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '58000:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: redoc_cv
        working_dir: /application
        volumes:
            - './app:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    elasticsearch:
        image: elasticsearch:7.9.2
        environment:
            - discovery.type=single-node
            # - bootstrap.memory_lock=true
            # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - ./elastic-data:/usr/share/elasticsearch/data